### PR TITLE
Make squares in group visible

### PR DESCRIPTION
**Pull request by madhug-nadig**
Put some stroke around the square. Removed the buggy x-axis timeline code. So the only change to the exsiting code base is the stroke. 

What'd you think @inodb ?

### CODE REVIEW

**Comment by inodb** [comment]
@madhug-nadig Thanks for the PR, I like the idea of a stroke around merged squares. Maybe a little thicker to make it more clear. It would be even better if the stroke was only around two sides of the rectangle, so it looks like a shadow, similar to the merged circle time point.

At the moment you apply the style to all rectangles (perhaps on purpose), the idea is to apply it only to square points that represent merged time points. For me to merge this PR the following things are necessary:
1. Change index.html such that there is a merged square time point i.e. multiple time points at the same day.
2. Only apply the styling to that merged square point

Thanks

**Comment by madhug-nadig** [comment]
I saw that when the circles are merged, the `display` is changed from `circle` to `dropshadow circle`. How does that work, @inodb ?

**Comment by madhug-nadig** [comment]
I tried applying that to all squares as a test(ie without merging the timepoints) and it does not work. 

`for(var iter =0; iter<allData.length; iter++){
        for(var j =0; j< allData[iter].times.length; j++){
          if(allData[iter].times[j].display=='square'){
              allData[iter].times[j].display = 'dropshadow square';
          }
        }
     }`

This is the code I used. Two simple for loops that change `square` to `dropshadow square`.

**Comment by madhug-nadig** [comment]
Also, the `trackData` in the `mergeTooltipTablesAtEqualTimepoint` function contains all data except the case where the `display` is set to squares. I am not sure why.. 

I think I am getting confused here, could you please help be sort this out?

**Comment by madhug-nadig** [comment]
@inodb  I will work on this a bit later.

**Pull request closed without merging**
