### PR TITLE
Vertical Line on Mouse over

### PR DESCRIPTION
**Pull request by madhug-nadig**
vertical line

This is the progress so far.  

Do let me know if there any changes @inodb .

### CODE REVIEW

**Comment by inodb** [comment]
Thanks. It would be nice to see the date where the vertical line is at. Ideally one would also be able to see the tooltips of the various points that the vertical line is moving over.

**Comment by madhug-nadig** [comment]
Great, I will start working on that.

Would you want the all of it in this PR itself?

**Comment by inodb** [comment]
Yes, please. I prefer to accept only complete features to prevent accumulating non functional code.

**Comment by madhug-nadig** [comment]
Hi @inodb , I have added the label on the line, please let me know if the position of the line is alright. 

I was not able to access the time values, so as a place holder, I've passed on the x_mouse value to the formatTime function. I initially thought of using the linear.invert(), however I could not file the scale. 
Any ideas on how I could resolve this?

Thanks

label on line

**Pull request closed without merging**
