### PR TITLE
Add conditions to transform clinical event type label

### PR DESCRIPTION
**Pull request by ngocnn1104**
# What? Why?
Add conditions to transform clinical event type label:
- If event type has mixed cases or is all uppercase with less than 5 characters, it will be kept intact;
- In other cases, event type is transformed by `capitalizeFirstLetterLowerCaseRest`.

# Notify reviewers
@inodb

### CODE REVIEW

**Review by inodb — APPROVED** [review]
THanks @ngocnn1104 - this code hasn't been changed in a while so not sure what the issue is with Travis CI exactly. Other than that this seems like a reasonable change to me

**Comment by inodb** [comment]
@ngocnn1104 Ah I see - the image upload service is broken ptpb.pw

**Comment by ngocnn1104** [comment]
> @ngocnn1104 Ah I see - the image upload service is broken ptpb.pw

@inodb so is it gonna be fixed soon? Should I wait until then and restart the build?

**Comment by inodb** [comment]
@ngocnn1104 maybe try to run the tests locally and see if you notice anything: https://github.com/cBioPortal/clinical-timeline/blob/master/.travis.yml. There are a few screenshot tests that don't seem to be working on Travis. Since this is a pretty minor change I don't want to block this PR over the CI tests not working, but would be good to do a sanity check. If u figure out the Travis CI problem: even better, but not necessary. When you run it locally you might see a few changes in styling compared to the reference screenshots: don't worry about those. I'm only interested in the actual errors. If there are none, we can merge it. Maybe comment in the PR on any issues in running the tests locally and update docs accordingly

**Comment by inodb** [comment]
I can't update the screenshot in the PR without push access, so going to merge

**Pull request merged**
